project:
  type: website

website:
  title: "De esto no hay tesis"
  site-url: https://www.nohaytesispodcast.com/
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: episodes.qmd
        text: Episodios
      - misc.qmd  
      - href: https://ko-fi.com/nohaytesispod
        text: Apóyanos
      - href: contacto.qmd
        text: Contacto
      - about.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/NoHayTesisPod
      - icon: instagram
        href: https://www.instagram.com/nohaytesispod/
      - icon: mastodon
        href: https://mast.lat/@nohaytesispod
      - icon: bluesky
        href: https://bsky.app/profile/nohaytesispod.bsky.social
      - icon: rss
        href: episodes.xml

format:
  html:
    theme: [darkly, custom.scss]
    css: styles.css
    toc: true



